name: belajar_bloc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.4
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  go_router: ^13.2.0
  http: ^1.2.0
  meta: ^1.10.0
  stream_transform: ^2.1.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
